version: '3.8'
services:
  db:
    image: postgres:15-alpine
    container_name: kata-postgres
    environment:
      POSTGRES_DB: altenkata
      POSTGRES_USER: kata_user
      POSTGRES_PASSWORD: kata_password
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "dss_user"]
      interval: 10s
      timeout: 5s
      retries: 5